## Numpy Array 

In [4]:
my_list = [1,2,3,4]  

In [5]:
import numpy as np
arr=np.array(my_list)# creating numpy array 

In [6]:
arr

array([1, 2, 3, 4])

In [7]:
my_mat= [[1,2,3],[4,5,6],[5,5,5]]

In [8]:
np.array (my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [5, 5, 5]])

In [9]:
np.arange (0,10) # starting and last point 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange (0,11,2) # qucikly generate array  using numpy

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros (3)

array([0., 0., 0.])

In [13]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones(4) # single dimensions 

array([1., 1., 1., 1.])

In [15]:
np.ones ((4,5)) # we can pass tuples for n diemensions 

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.linspace (0,5,10) # 10 evenly space pointes from 0 to 5c 

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [17]:
np.eye(4) # gives identity matrix 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.random.rand(5)

array([0.54876139, 0.85912453, 0.80085865, 0.0572591 , 0.65271481])

In [20]:
np.random.rand (5,5)

array([[0.91428236, 0.56830573, 0.90248836, 0.53413099, 0.2994716 ],
       [0.472013  , 0.88051874, 0.84056281, 0.776385  , 0.1015898 ],
       [0.71296401, 0.74463952, 0.86018941, 0.66237804, 0.42781742],
       [0.97615868, 0.01616428, 0.49676398, 0.8914076 , 0.43951688],
       [0.06687926, 0.28345792, 0.74781357, 0.56248839, 0.22487045]])

In [21]:
np.random.randn(2) # it will return number from std distribution // here we need not to pass tuples

array([-0.10278717,  0.69684874])

In [23]:
np.random.randn(2,2)

array([[ 0.71819951,  0.36744851],
       [ 0.11681211, -0.02036606]])

In [24]:
np.random.randint (1,100,10)

array([90, 91, 87, 60, 26, 18, 18, 29, 92, 12])

In [25]:
arr=np.arange (25)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
ranarr=np.random.randint (0,50,10) # ten random array between the range 0 to 50

In [30]:
ranarr

array([ 2, 24, 39, 31,  9, 14, 13, 11,  7, 34])

In [35]:
arr.reshape (5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
ranarr.reshape (2,5)

array([[ 2, 24, 39, 31,  9],
       [14, 13, 11,  7, 34]])

In [37]:
ranarr.max()

39

In [38]:
arr.max()

24

In [39]:
ranarr

array([ 2, 24, 39, 31,  9, 14, 13, 11,  7, 34])

In [40]:
ranarr.argmin ()

0

In [41]:
ranarr.argmax()

2

In [43]:
arr.shape

(25,)

In [44]:
arr= arr.reshape (5,5)

In [45]:
arr.shape 

(5, 5)

In [46]:
arr.dtype 

dtype('int32')

In [47]:
from numpy.random import randint  # we can do like this also 

In [49]:
randint (2,10)


5

 ## NumPy Indexing & selection 
 
 we will see how to select and group of elements 

In [50]:
import numpy as np
arr=np.arange(0,11)

In [51]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
# accesing element 
arr[8]

8

In [54]:
arr[1:9]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [56]:
arr[0:6] # it will access upto 5 or before 6

array([0, 1, 2, 3, 4, 5])

In [57]:
arr[5:] # grab upto last after 5 

array([ 5,  6,  7,  8,  9, 10])

In [58]:
arr[:5] 

array([0, 1, 2, 3, 4])

In [60]:
arr[0:5] = 100 

In [61]:
arr  

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [62]:
arr = np.arange (0,11)

In [63]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
slice_of_arr= arr[0:6]

In [65]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [66]:
slice_of_arr[:]=99

In [67]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [68]:
arr_copy =arr.copy()

In [69]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [70]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [71]:
arr_copy[:]=100

In [72]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [73]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [74]:
# creating 2d array 

In [75]:
arr_2d= np.array ([[5,6,8],[3,3,32],[33,44,44]])

In [76]:
arr_2d

array([[ 5,  6,  8],
       [ 3,  3, 32],
       [33, 44, 44]])

In [79]:
#let us grab 5 
arr_2d[0][0] 

5

In [93]:
arr_2d[1,1]

3

In [95]:
arr_2d[2,1]

44

In [96]:
arr_2d[2,0] # grab from 2nd row and 0th col 

33

In [98]:
arr_2d[2][0] # both are same 

33

In [99]:
arr_2d

array([[ 5,  6,  8],
       [ 3,  3, 32],
       [33, 44, 44]])

In [100]:
arr_2d[1:2,0:2]

array([[3, 3]])

In [101]:
# grab 3,32,44,44
arr_2d[1:,1:]

array([[ 3, 32],
       [44, 44]])

In [105]:
# grab col 2nd 
arr_2d[:,1:2]

array([[ 6],
       [ 3],
       [44]])

In [107]:
#grab 1st and 2nd row 
arr_2d[0:2,:]

array([[ 5,  6,  8],
       [ 3,  3, 32]])

In [108]:
# conditional selection 
arr= np.arange (0,11)

In [109]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [110]:
arr>5 # it will return boll value 

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [112]:
bool_arr= arr>5

In [113]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [114]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [115]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [116]:
arr[arr<3] # varible inside variable 

array([0, 1, 2])

In [117]:
arr_2d= np.arange (50).reshape (5,10)

In [118]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [122]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [123]:
#grab 4th row 
arr_2d[3:4,:]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

## Numpy Operations 
* Array with array 
* Array with scalar 
* universal array function 

In [135]:
import numpy as np
arr= np.arange (0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [136]:
arr+arr # array is getting double 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [137]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0])

In [138]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576])

In [139]:
arr/arr # because of nan we are getting warnong 

C:\Users\pskj0\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [141]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124])

In [142]:
arr-1

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22, 23])

In [143]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [144]:
1/arr # because of infinity we are getting warning 

C:\Users\pskj0\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667, 0.0625    , 0.05882353, 0.05555556, 0.05263158,
       0.05      , 0.04761905, 0.04545455, 0.04347826, 0.04166667])

In [145]:
arr**2 

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576],
      dtype=int32)

In [146]:
# universal function 

In [147]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949])

In [148]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
       2.64891221e+10])

In [149]:
np.max(arr)

24

In [150]:
arr.max()

24

In [151]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721,
        0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836])

In [153]:
np.log(arr) # because of negetive intinity we are getting warning 

C:\Users\pskj0\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383])

In [154]:
# you can visit the documentation and various fun of universal function on the numpy website 

In [155]:
# problem 

ques 1 : import numpy as np 

In [156]:
import numpy as np

2. create an arry of 10 zeros

In [157]:
np.zeros (10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. create an arry of 10 ones

In [158]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

ques : create an array of 10 fives 

In [194]:
arr=np.arange(0,10)

In [195]:
slice_arr = arr[0:]

In [196]:
slice_arr[:]=5

In [197]:
arr

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [241]:
np.arange (10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [242]:
np.arange (10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [204]:
a=np.arange(0,9)

In [205]:
a.reshape (3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [206]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [213]:
np.random.rand (1)

array([0.56475182])

In [215]:
np.random.randn(5,5)

array([[-0.28357766,  2.33748313, -1.42857354,  0.46509117, -0.23460298],
       [-1.41603684,  0.41089958, -0.34848733,  1.19090503, -0.97101569],
       [-0.36619122, -0.61146053,  0.11935825,  0.59827181, -0.78255463],
       [-0.34200944, -1.24743648, -1.65209766, -1.15913481, -0.53787532],
       [-1.50071288, -0.5878657 , -1.15976279, -0.41739327, -0.36483156]])

In [243]:
np.arange(1,101).reshape(10,10) / 100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [230]:
np.linspace (0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [231]:
mat= np.arange (1,26).reshape (5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [232]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [234]:
mat[3,4]

20

In [236]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [237]:
mat[4]

array([21, 22, 23, 24, 25])

In [238]:
mat[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [239]:
mat.sum()

325

In [240]:
mat.std()

7.211102550927978

In [244]:
mat.sum(axis=0) # get the sum of all columns in mat

array([55, 60, 65, 70, 75])

In [246]:
mat.sum(axis=1) # get the sum of all rows in mat

array([ 15,  40,  65,  90, 115])